### ISSUE TITLE
Créer une page Wiki

### ISSUE THREAD

**Issue by cedryc-ruth** [Baatezus/caviste#8]
Il faudrait créer une page dans le Wiki pour présenter et expliquer l'utilisation de l'application.
Voici un [exemple de Wiki:](https://github.com/NatLibFi/Skosmos/wiki)

Exemple de table des matières:
* page _Home_
* page _Installation_
* page _Utilisation_

**Comment by Baatezus** [comment]
Le Wiki est complété.
