### ISSUE TITLE
Créer une première release

### ISSUE THREAD

**Issue by cedryc-ruth** [Baatezus/caviste#9]
Il est grand temps de [faire une _release_](https://help.github.com/articles/creating-releases/) même si toutes les fonctionnalités ne sont pas encore implémentées.

**N'oubliez pas de créer un tag en respectant les [conventions de versioning](http://semver.org/).**

**Comment by Baatezus** [comment]
La [première release](https://github.com/Baatezus/caviste/releases) est disponible.
